// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseManagement.Data;

#nullable disable

namespace WarehouseManagement.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20250922223724_int1")]
    partial class int1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WarehouseManagement.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 727, DateTimeKind.Local).AddTicks(6943),
                            Description = "أجهزة كمبيوتر وملحقاتها",
                            Name = "أجهزة كمبيوتر"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 727, DateTimeKind.Local).AddTicks(7209),
                            Description = "كراسي ومكاتب وخزائن",
                            Name = "أثاث مكتبي"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 727, DateTimeKind.Local).AddTicks(7211),
                            Description = "أوراق وأقلام ومستلزمات مكتبية",
                            Name = "قرطاسية"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 727, DateTimeKind.Local).AddTicks(7213),
                            Description = "أجهزة كهربائية متنوعة",
                            Name = "أجهزة كهربائية"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 727, DateTimeKind.Local).AddTicks(7215),
                            Description = "مواد ومستلزمات التنظيف",
                            Name = "مواد تنظيف"
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Building")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<int?>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Building = "المبنى الرئيسي",
                            Code = "WH-01",
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5192),
                            Floor = 1,
                            MaxCapacity = 1000,
                            Name = "المخزن الرئيسي",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Building = "المبنى الرئيسي",
                            Code = "OF-01",
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5437),
                            Floor = 2,
                            Name = "مكتب الإدارة",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Building = "المبنى الفرعي",
                            Code = "WS-01",
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5439),
                            Floor = 1,
                            Name = "ورشة الصيانة",
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            Building = "المبنى الرئيسي",
                            Code = "MR-01",
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5442),
                            Floor = 3,
                            Name = "غرفة الاجتماعات",
                            Type = 5
                        },
                        new
                        {
                            Id = 5,
                            Building = "المبنى الفرعي",
                            Code = "LB-01",
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5445),
                            Floor = 2,
                            Name = "المختبر",
                            Type = 4
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "COMP-001",
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5565),
                            Description = "جهاز كمبيوتر مكتبي",
                            LastUpdated = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5565),
                            LocationId = 1,
                            Name = "جهاز كمبيوتر ديل",
                            Price = 2500.00m,
                            Quantity = 10,
                            Unit = "قطعة"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Code = "CHAIR-001",
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5565),
                            Description = "كرسي مكتبي دوار",
                            LastUpdated = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5565),
                            LocationId = 1,
                            Name = "كرسي مكتبي",
                            Price = 450.00m,
                            Quantity = 25,
                            Unit = "قطعة"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Code = "PAPER-001",
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5565),
                            Description = "ورق طباعة أبيض",
                            LastUpdated = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5565),
                            LocationId = 1,
                            Name = "ورق A4",
                            Price = 25.00m,
                            Quantity = 5,
                            Unit = "علبة"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Code = "PRINT-001",
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5565),
                            Description = "طابعة ليزر أحادية",
                            LastUpdated = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5565),
                            LocationId = 2,
                            Name = "طابعة ليزر",
                            Price = 1800.00m,
                            Quantity = 3,
                            Unit = "قطعة"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Code = "CLEAN-001",
                            CreatedDate = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5565),
                            Description = "مطهر أرضيات معطر",
                            ExpiryDate = new DateTime(2025, 10, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5565),
                            LastUpdated = new DateTime(2025, 9, 23, 1, 37, 23, 728, DateTimeKind.Local).AddTicks(5565),
                            LocationId = 1,
                            Name = "مطهر أرضيات",
                            Price = 15.00m,
                            Quantity = 2,
                            Unit = "لتر"
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ConfirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromLocationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ToLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransferredBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ToLocationId");

                    b.ToTable("Transfers", t =>
                        {
                            t.HasCheckConstraint("CK_Transfer_DifferentLocations", "[FromLocationId] <> [ToLocationId]");
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.Material", b =>
                {
                    b.HasOne("WarehouseManagement.Models.Category", "Category")
                        .WithMany("Materials")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.Location", "Location")
                        .WithMany("Materials")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Transfer", b =>
                {
                    b.HasOne("WarehouseManagement.Models.Location", "FromLocation")
                        .WithMany()
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.Location", "ToLocation")
                        .WithMany()
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromLocation");

                    b.Navigation("Material");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Category", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Location", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
